-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 20:08:40 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ondevaiserdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ondevaiserdb` ;

-- -----------------------------------------------------
-- Schema ondevaiserdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ondevaiserdb` DEFAULT CHARACTER SET utf8 ;
USE `ondevaiserdb` ;

-- -----------------------------------------------------
-- Table `ondevaiserdb`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`Usuarios` (
  `idUsuarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ondevaiserdb`.`TipoLocal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`TipoLocal` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`TipoLocal` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nome_tipo` TEXT NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ondevaiserdb`.`Local`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`Local` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`Local` (
  `idLocal` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `nomeLocal` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `endLocal` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `TipoLocal_id_tipo` INT NOT NULL,
  PRIMARY KEY (`idLocal`, `Usuarios_idUsuarios`),
  INDEX `fk_Local_Usuarios_idx` (`Usuarios_idUsuarios` ASC),
  INDEX `fk_Local_TipoLocal1_idx` (`TipoLocal_id_tipo` ASC),
  CONSTRAINT `fk_Local_Usuarios`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `ondevaiserdb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Local_TipoLocal1`
    FOREIGN KEY (`TipoLocal_id_tipo`)
    REFERENCES `ondevaiserdb`.`TipoLocal` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ondevaiserdb`.`CaracGeral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`CaracGeral` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`CaracGeral` (
  `idCaracGeral` INT NOT NULL AUTO_INCREMENT,
  `nomeCarac` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCaracGeral`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ondevaiserdb`.`CaracLocal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`CaracLocal` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`CaracLocal` (
  `Local_idLocal` INT NOT NULL,
  `Local_Usuarios_idUsuarios` INT NOT NULL,
  `CaracGeral_idCaracGeral` INT NOT NULL,
  PRIMARY KEY (`Local_idLocal`, `Local_Usuarios_idUsuarios`, `CaracGeral_idCaracGeral`),
  INDEX `fk_CaracLocal_CaracGeral1_idx` (`CaracGeral_idCaracGeral` ASC),
  CONSTRAINT `fk_CaracLocal_Local1`
    FOREIGN KEY (`Local_idLocal` , `Local_Usuarios_idUsuarios`)
    REFERENCES `ondevaiserdb`.`Local` (`idLocal` , `Usuarios_idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CaracLocal_CaracGeral1`
    FOREIGN KEY (`CaracGeral_idCaracGeral`)
    REFERENCES `ondevaiserdb`.`CaracGeral` (`idCaracGeral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ondevaiserdb`.`Favoritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`Favoritos` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`Favoritos` (
  `idFavoritos` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Local_idLocal` INT NOT NULL,
  PRIMARY KEY (`idFavoritos`, `Usuarios_idUsuarios`, `Local_idLocal`),
  INDEX `fk_Favoritos_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  INDEX `fk_Favoritos_Local1_idx` (`Local_idLocal` ASC),
  CONSTRAINT `fk_Favoritos_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `ondevaiserdb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favoritos_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `ondevaiserdb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ondevaiserdb`.`ComentImoveis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`ComentImoveis` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`ComentImoveis` (
  `idComentImoveis` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NOT NULL,
  `data` DATE NOT NULL,
  `nota` INT NOT NULL,
  `Local_idLocal` INT NOT NULL,
  PRIMARY KEY (`idComentImoveis`),
  INDEX `fk_ComentImoveis_Local1_idx` (`Local_idLocal` ASC),
  CONSTRAINT `fk_ComentImoveis_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `ondevaiserdb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ondevaiserdb`.`locacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ondevaiserdb`.`locacoes` ;

CREATE TABLE IF NOT EXISTS `ondevaiserdb`.`locacoes` (
  `idlocacoes` INT NOT NULL AUTO_INCREMENT,
  `Usuarios_idUsuarios` INT NOT NULL,
  `Local_idLocal` INT NOT NULL,
  PRIMARY KEY (`idlocacoes`, `Usuarios_idUsuarios`, `Local_idLocal`),
  INDEX `fk_locacoes_Usuarios1_idx` (`Usuarios_idUsuarios` ASC),
  INDEX `fk_locacoes_Local1_idx` (`Local_idLocal` ASC),
  CONSTRAINT `fk_locacoes_Usuarios1`
    FOREIGN KEY (`Usuarios_idUsuarios`)
    REFERENCES `ondevaiserdb`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacoes_Local1`
    FOREIGN KEY (`Local_idLocal`)
    REFERENCES `ondevaiserdb`.`Local` (`idLocal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
